project:
  type: website
  output-dir: docs
  
website:
  title: "Sue-Ellen Duffy"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/duffysueellen/Sue-Ellen_Data_Experience
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, YOUR NAME"

format:
  html:
    theme: cerulean
    toc: true

editor: source

resources:
  - "files/**"