---
title: "Projects"
---

## Predicting Stroke with Synthetic Data
Machine Learning - Fall 2024 - <a href="files/Predicting_Stroke_Report_2024.pdf"
target="_blank">Report</a>

```{r echo=FALSE}
#<a href="files/dashboard.html"
#target="_blank">Stroke Prediction Dashboard</a>
```

Predicted stroke using a synthetic sample of electronic health records (EHR), meant to represent people ages 30-70 from Massachusetts using machine learning. As a data analyst working in education and health fields, I wanted to explore machine learning within the context of predicting outcomes in specific populations. 

## Reddit Vaccine Discourse: Cross-Vaccine (HPV, MMR, COVID), Cross-Time (2005-2023)
Independent Research - Argument Analysis - Fall 2024 

Analyzed online vaccine hesitancy trends using natural language processing (NLP) to explore the "spillover effect" of COVID-19 vaccine attitudes on other vaccines, based on a Reddit corpus. This ongoing research is in collaboration with UMass researchers and is in the pre-publication stage.

## Syringe Service Program (SSP) Evaluation Plan
Program Evaluation - Spring 2024 <a href="files/SSP Evaluation Plan.pdf"
target="_blank">Program Evaluation</a>

Developed a program evaluation for assessing the impact of Syringe Service Programs (SSPs) on reducing HIV rates and improving health outcomes for people who use drugs (PWUD), with a focus on data-driven decision-making for state-funded harm reduction programs.

*Maine’s Unified Data Warehouse (MUD) is a fictional warehouse which I piloted in my time working at Maine's Office of Behavioral Health. This evaluation was not commissioned by the State of Maine*

## Exploring Relationships and Centralities in Healthcare Networks of People Who Use Drugs (PWUD)
Social Networks - Spring 2024 -  <a href="files/Sue-Ellen_Duffy_SN_Spring_2024.svg"
target="_blank">Poster</a>

Explored healthcare journeys of people who use drugs (PWUD) using synthetic electronic health records (EHR), mapping their patient, provider relationships.The average recovery journey for a PWUD lasts over ten years and involves 6 treatment episodes. This project serves as an introduction to understanding patient-provider encounters of PWUD and as a template for future analysis.

## A Sentiment-Based Exploration of Glassdoor Reviews in US Companies with Unlimited PTO Policies
Text as Data - Fall 2023 - <a href="files/Sue-Ellen_Duffy_TAD_Fall_2023.svg"
target="_blank">Poster</a>

Conducted sentiment-based text analysis to compare employees' written reviews with their star ratings, evaluating alignment and satisfaction regarding paid time off.

## Boston Crash Trends 2012-2022
Data Fundamentals - Spring 2023 - <a href="https://dacss.github.io/601_Spring_2023/posts/Sue-EllenDuffy_Final_Project.html" 
target="_blank">Exploratory Analysis</a>

Performed exploratory data analysis on car crash data in Boston from the Massachusetts Department of Transportation, marking my first experience using R for data coding and analysis, with a focus on basic exploratory techniques.
